"""initial schema

Revision ID: ae32cbf33580
Revises: 
Create Date: 2026-08-17 09:53:31.901473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae32cbf33580'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_email', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)

    op.create_table('bank_configurations',
    sa.Column('bank_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('api_key_header_name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('cost_weight', sa.Float(), nullable=False),
    sa.Column('circuit_breaker_threshold', sa.Float(), nullable=False),
    sa.Column('rolling_uptime_percent', sa.Float(), nullable=False),
    sa.Column('avg_latency_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('bank_id')
    )
    op.create_table('consent_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('fin', sa.String(length=14), nullable=False),
    sa.Column('kyc_level', sa.String(length=20), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('consent_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_tokens_fin'), ['fin'], unique=False)

    op.create_table('consents',
    sa.Column('consent_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('app_id', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('consent_id')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_consents_username'), ['username'], unique=False)

    op.create_table('developer_apps',
    sa.Column('app_id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('app_name', sa.String(length=100), nullable=False),
    sa.Column('merchant_name', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('allowed_scopes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('app_id'),
    sa.UniqueConstraint('client_id')
    )
    with op.batch_alter_table('developer_apps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_developer_apps_merchant_id'), ['merchant_id'], unique=False)

    op.create_table('fee_rules',
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('bank_id', sa.String(length=20), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fee_type', sa.String(length=20), nullable=False),
    sa.Column('flat_fee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('percentage_bps', sa.Integer(), nullable=False),
    sa.Column('min_fee', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_fee', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('revenue_share_bps', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('rule_id', 'version')
    )
    with op.batch_alter_table('fee_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_rules_is_active'), ['is_active'], unique=False)

    op.create_table('fin_vault',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('fin_blind_index', sa.String(length=64), nullable=False),
    sa.Column('fin_ciphertext', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    with op.batch_alter_table('fin_vault', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fin_vault_fin_blind_index'), ['fin_blind_index'], unique=True)

    op.create_table('kyb_requests',
    sa.Column('kyb_id', sa.String(length=64), nullable=False),
    sa.Column('developer_name', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=False),
    sa.Column('requested_scopes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('kyb_id')
    )
    op.create_table('ledger_entries',
    sa.Column('entry_id', sa.String(length=64), nullable=False),
    sa.Column('transaction_ref', sa.String(length=128), nullable=False),
    sa.Column('account_ref', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.String(length=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_mirror', sa.Boolean(), nullable=False),
    sa.Column('bank_id', sa.String(length=20), nullable=True),
    sa.Column('payment_id', sa.String(length=64), nullable=True),
    sa.Column('app_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('entry_id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_account_ref'), ['account_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_bank_id'), ['bank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_is_mirror'), ['is_mirror'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_transaction_ref'), ['transaction_ref'], unique=False)

    op.create_table('linked_accounts',
    sa.Column('link_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('bank_id', sa.String(length=20), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('is_default_sending', sa.Boolean(), nullable=False),
    sa.Column('is_default_receiving', sa.Boolean(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('link_id')
    )
    with op.batch_alter_table('linked_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_linked_accounts_username'), ['username'], unique=False)

    op.create_table('merchants',
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('kyb_status', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('selected_rail', sa.String(length=20), nullable=True),
    sa.Column('bank_order_reference', sa.String(length=128), nullable=True),
    sa.Column('consent_token', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.String(length=512), nullable=True),
    sa.Column('debtor_account_number', sa.String(length=30), nullable=False),
    sa.Column('debtor_bank_id', sa.String(length=20), nullable=False),
    sa.Column('creditor_account_number', sa.String(length=30), nullable=False),
    sa.Column('creditor_bank_id', sa.String(length=20), nullable=False),
    sa.Column('creditor_name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('end_to_end_id', sa.String(length=64), nullable=False),
    sa.Column('remittance_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('payment_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_end_to_end_id'), ['end_to_end_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_payment_id'), ['payment_id'], unique=False)

    op.create_table('user_app_identities',
    sa.Column('psu_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('app_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('psu_id'),
    sa.UniqueConstraint('username', 'app_id', name='uq_user_app_identity')
    )
    with op.batch_alter_table('user_app_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_app_identities_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_app_identities_username'), ['username'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('fin', sa.String(length=14), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('failed_pin_attempts', sa.Integer(), nullable=False),
    sa.Column('pin_locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_fin'), ['fin'], unique=True)

    op.create_table('webhook_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=False),
    sa.Column('webhook_url', sa.String(length=512), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_payment_id'), ['payment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_payment_id'))

    op.drop_table('webhook_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_fin'))

    op.drop_table('users')
    with op.batch_alter_table('user_app_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_app_identities_username'))
        batch_op.drop_index(batch_op.f('ix_user_app_identities_app_id'))

    op.drop_table('user_app_identities')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payments_end_to_end_id'))

    op.drop_table('payments')
    op.drop_table('merchants')
    with op.batch_alter_table('linked_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_linked_accounts_username'))

    op.drop_table('linked_accounts')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_transaction_ref'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_payment_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_is_mirror'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_created_at'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_bank_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_app_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_account_ref'))

    op.drop_table('ledger_entries')
    op.drop_table('kyb_requests')
    with op.batch_alter_table('fin_vault', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fin_vault_fin_blind_index'))

    op.drop_table('fin_vault')
    with op.batch_alter_table('fee_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_rules_is_active'))

    op.drop_table('fee_rules')
    with op.batch_alter_table('developer_apps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_developer_apps_merchant_id'))

    op.drop_table('developer_apps')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_username'))
        batch_op.drop_index(batch_op.f('ix_consents_status'))
        batch_op.drop_index(batch_op.f('ix_consents_app_id'))

    op.drop_table('consents')
    with op.batch_alter_table('consent_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_tokens_fin'))

    op.drop_table('consent_tokens')
    op.drop_table('bank_configurations')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
